id: A3450A3EB
title: Prayer for the Swift Rebirth of Jamyang Khyenrab Tayé
type: translation
pechas:
- IEB07F8DB
- I99C24769
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:02:52.087926
  last_modified_at: 2023-01-04 12:02:52.087943
  collections:
  - Jamyang Khyenrab Tayé Series
  - Works of Tibetan Masters
alignment_to_base:
  IEB07F8DB/36F4: A852
  I99C24769/5F34: A852
